mutation CreateInstitution($input: CreateInstitutionInput!) {
	createInstitution(input: $input) {
		id
		name
	}
}

mutation UpdateInstitution($input: UpdateInstitutionInput!) {
	updateInstitution(input: $input) {
		id
		name
	}
}

mutation AddPropertyValuation($propertyId: ID!, $input: AddValuationInput!) {
	addPropertyValuation(propertyId: $propertyId, input: $input) {
		id
	}
}

mutation UpdatePropertyValuation($input: UpdateValuationInput!) {
	updateValuation(input: $input) {
		id
	}
}

mutation DeleteInstitution($id: ID!) {
	deleteInstitution(id: $id) {
		id
	}
}