query ListProperties($first: Int!, $page: Int, $search: String) {
    properties(first: $first, page: $page, search: $search) {
        data {
            id
            name
            exactAddress
            latitude
            longitude
            latestValuation {
                measuredAt
                institution {
                    name
                }
            }
            quantity
        }
        paginatorInfo {
            currentPage
            lastPage
            total
        }
    }
}

query GetPropertyById($id: ID!) {
    propertyById(id: $id) {
        id
        name
        owner
        exactAddress
        latitude
        longitude
        quantity
        valuations {
            id
            averageValue
            measuredAt
            landArea
            improvementArea
            landValue
            utilizationRatio
            averageSquareYard
            averageSquareMeter
            riskProfile
            institution {
                id
                name
            }
            user {
                id
                name
            }
        }
    }
}