query ListProperties($first: Int!, $page: Int, $search: String) {
    properties(first: $first, page: $page, search: $search) {
        data {
            id
            name
            exactAddress
            cadastralKey
            latitude
            longitude
            latestValuation {
                measuredAt
                institution {
                    name
                }
            }
            quantity
        }
        paginatorInfo {
            currentPage
            lastPage
            total
        }
    }
}

query GetPropertyById($id: ID!) {
    propertyById(id: $id) {
        id
        name
        exactAddress
        cadastralKey
        latitude
        longitude
        quantity
        latestValuation {
            id
        }
        valuations {
            id
            owner
            applicant
            phone
            sector
            averageValue
            measuredAt
            landArea
            improvementArea
            landValue
            utilizationRatio
            averageSquareYard
            averageSquareMeter
            riskProfile
            institution {
                id
                name
            }
            user {
                id
                name
            }
        }
    }
}

query GetPropertiesWithinRadius($latitude: Float!, $longitude: Float!, $radiusMeters: Int!) {
    propertiesWithinRadius(latitude: $latitude, longitude: $longitude, radiusMeters: $radiusMeters) {
        id
        name
        cadastralKey
        exactAddress
        latitude
        longitude
    }
}

fragment PropertyPointFields on Property {
    id
    name
    exactAddress
    cadastralKey
    latitude
    longitude
    quantity
    latestValuation {
        sector
        averageValue
        landArea
        improvementArea
        landValue
        utilizationRatio
        averageSquareYard
        averageSquareMeter
        riskProfile
        measuredAt
    }
}

query PropertiesWithinBounds($northLatitude: Float!, $eastLongitude: Float!, $southLatitude: Float!, $westLongitude: Float!, $limit: Int) {
    propertiesWithinBounds(northLatitude: $northLatitude, eastLongitude: $eastLongitude, southLatitude: $southLatitude, westLongitude: $westLongitude, limit: $limit) {
        ...PropertyPointFields
    }
}